dict_saint = {
    "marxiô": "ma rơ xi ô",
    "marơxiô": "ma rơ xi ô",
    "uliriô":"u li ri ô",
    "uliro":"u li rô",
    "Cantuarensi":"can tua ren si",
    "ethêriđô":"e thê ri đô",
    "êđuađô":"ê đu đô",
    "rômanô":"rô man ô",
    "nosia":"no si a",
    "Bênêđichtô":"bê nê đich tô",
    "biêntô":"biên tô",
    "nivêla":"ni vê la",
    "útăng":"ú tăng",
    "giêrituduđê":"giê ri tu du đê",
    "garasa":"ga ra sa",
    "italia":"i ta li a",
    "phavi":"pha vi",
    "xibêlina": "xi bê li na",
    "đamasênô":"đa ma sê nô",
    "đốctôrê":"đốc tô rê",
    "đamacô":"đa ma cô",
    "maisen":"mai sen",
    "amêđê": "a mê đê",
    "maiseen":"mai sen",
    "henvesia": "hen vê xia",
    "henvêxia": "hen vê xia",
    "giuse": "diu xê",
    "giuseu": "giê su",
    "uriio": "u li ri ô",
    "uliro": "u li ri ô",
    "amè":"a mê đê",
    "saboaia": "sa bao dia",
    "Nicolasau": "Ni cô lao",
    "maria":"ma ri a",
    "phêrô": "phê rô",
    "nicolao": "Ni cô lao",
    "tremphilithianô": "trem phi li thi a nô",
    "tremphilythianô": "trem phi li thi a nô",
    "milanô": "mi la nô",
    "giêsu": "giê su",
    "kirixitô": "ki ri xi tô",
    "amen": "a men",
    "italia": "y ta ly a",
    "amrôxiô": "am rô xay ô",
    "aucutinh": "ao cu tinh",
    "rôma": "rô ma",
    "mariô": "ma di ô",
    "vitôđinô": "vi tô đi nô",
    "ighêrêgia": "y ghế rê xa",
    "đamasô": "da mã sô",
    "phanchicô": "phan chi cô",
    "phaola": "phao la",
    "giusê": "diu xê",
    "Khêrôkhiô": "khê rê khi ô",
    "Isidôrô": "I si đô rô",
    "visentê": "vi sen tê",
    "phêrêđiê": "phê rê đi ê",
    "Sotyđôrô": "so ty đô rô",
    "Alêphunsô": "a lê phun sô",
    "valenthia": "va len thi a",
    "alécxăngrôđô": "a léc xăng rô đô",
    "savilianô": "sa vi la nô",
    "dalômathia": "da lô ma thi a",
    "riôkilithianô": "ri ô ki li thi a nô",
    "evan": "ê van",
    "vitôdinô": "vi tô di nô",
    "Lêanđôđô": "lê an đô đô",
    "aletsangrôdô": "a let sang rô dô",
    "inquisitôdê": "in qui si tô dê",
    "giêrônimô": "khê rô ni mô",
    "phêlakhêô": "phê la khê ô",
    "saxerdotê": "se xe r do tê",
    "Erminêkhilidô": "e r mi nê khi li dô",
    "adalobertô": "a đa lô bớt tô",
    "Tyburthiô": "ty bu r thi ô",
    "Vêdona": "vê do na",
    "kêlêtô": "kê lê tô",
    "linô": "li nô",
    "Xexilia": "xe xay li a",
    "biênxisong": "bi ên xi song",
    "Đô mi thi a nô": "đô mi thi a nô",
    "sôtiđôrô": "sô ti đô rô",
    "alet": "a lét",
    "sandođô": "san do đô",
    "ebiênthiô": "e biên thi ô",
    "tyôdolô": "ty ô dau lo",
    "antôniô": "an tô ni ô",
    "phabôn": "pha bôn",
    "lêô": "lê ô",
    "đốctôrê": "đốc tô rê",
    "aliphiô": "a li phi ô",
    "margarita": "mã gái nhà đi",
    "ngônrthalê": "ngôn rĩ tha lê",
    "ermênê": "e rĩ khen nề",
    "ermine": "e rĩ khen nề",
    "khilôdô": "khi ly do",
    "khilidô": "khi ly do",
    "typhôrthiô": "ty thi ô",
    "tyburthiô": "ty thi ô",
    "valêrianô": "va lê ri a nô",
    "Mắcximô": "mắc xi mô",
    "calađa": "ca la đa",
    "anithiô": "a ni thi ô",
    "phiđêly": "phi đê ly",
    "batôlamiêu": "ba tô la miêu",
    "anxilômô": "an xi lô mô",
    "tuô": "tu ô",
    "Sotidôrô": "so ti đô rô",
    "cletêô": "cờ le tê ô",
    "Hermênêkhilôđô": "he r mê nê khi lô dô",
    "Phiđêli": "phi đê li",
    "Rosariô": "ro sa ri ô",
    "khêrkhiô": "khê r khi ô",
    "marcô": "mac cô",
    "marc": "mác",
    "ghêrêgôriô": "ghê rê gô ri ô",
    "Vênêthia": "vê nê thi a",
    "marthilinô": "ma rờ thi li nô",
    "turibiô": "tu rờ bi ô",
    "Alecsơnria": "a lec sơn ria",
    "Bảolộc": "bảo lộc",
    "vitaly": "vi ta ly",
    "phêrô": "phê rô",
    "catarina": "ca ta ri na",
    "catađina": "ca ta đi na",
    "siêna": "si ê na",
    "phiô": "phi ô",
    "anselômo": "an se lô mo",
    "khêorkhiô": "khê o r khi ô",
    "Pholônia": "pho lô nia",
    "dominhgô": "do minh cô",
    "đominhgô": "do minh cô",
    "vít vồ": "viết vồ",
    "dôminhgô": "do minh cô",
    "bêtôdonila": "bê tô đô ni la",
    "betxayda": "bê tay đa",
    "Anrê": "An rê",
    "Anrêđô": "An rê đô",
    "Phêrôphêta": "Phê rô phê ta",
    "Natanae": "Na ta na ê",
    "Alecsanria": "A lét san ri a",
    "Alecsando": "A lét san đô",
    "Constantinopholy": "Con stan ti nô phô li",
    "Êlêna": "Ê lê na",
    "Mônica": "Mô ni ca",
    "Amlôxiô": "Am lô xi ô",
    "Cardinalé": "Car di na lê",
    "Rosario": "Ro sa ri ô",
    "Isave": "I sa vê la",
    "Giuan": "Giô an",
    "Giébédéo": "Giê bê đê ô",
    "Giédônimo": "Giê đô ni mô",
    "Mighé Aricanté": "Mi ghê A ri can tê",
    "Ghérégérié": "Ghê rê gê ri ê",
    "Caphadóthia": "Ca pha đô thi a",
    "Stanislao": "sờ ta ni sờ lao",
    "Innothenthio": "In nô thên thi ô",
    "Phutughé": "Phu tu ghê",
    "Boniphatié": "Bo ni pha ti ê",
    "Philiphé": "Phi li phê",
    "Phatscali Bayong": "Phat ca li Ba dông",
    "Pholodenthia": "Pho lo đên thi a",
    "Pholodentia": "Pho lo đên thi a",
    "anataxiô": "a na ta xi ô",
    "macô": "ma cô",
    "coranô": "co ra nô",
    "aricantô": "a ri can tô",
    "mighê": "mi ghê",
    "coranô": "co ra nô",
    "alylôtô": "a ly lô tô",
    "nêphômôthiđô": "nê phô mô thi đô",
    "phatcabayông": "phat ca ba yông",
    "phuđenthiana": "phu đen thi a na",
    "ghêrê": "ghê rê",
    "khiliêlômô": "khi li ê lô mô",
    "sêlestinô": "sê le s ti nô",
    "venanthiô": "ve nan thi ô",
    "nêphômôthiđô": "nê phô mô thi đô",
    "sivevatio": "si ve va ti ô",
    "bernar": "be nar",
    "rius": "ri us",
    "bartômia": "ba to mi a",
    "khiliêlômô": "khi li ê lô mô",
    "pherdinanđô": "phe r di nan đô",
    "nadarét": "na da rết",
    "thiphas": "thi pha s",
    "galilêa": "ga li lê a",
    "phêrô": "phê rô",
    "dútsthitia": "dút sthi ti a",
    "dútxitia": "dút xi ti a",
    "ôlivêtê": "ô li vê tê",
    "giêrusalem": "giê ru sa lem",
    "antôninô": "an tô ni nô",
    "vít": "viết",
    "stanilao": "sờ ta ni lao",
    "gio ana": "dô an",
    "bergamô": "bê ga mô",
    "nêriô": "nê ri ô",
    "ekhiriô": "ê khi ri ô",
    "bôniphathiô": "bô ni pha thi ô",
    "ghêrêgôriôvít": "ghê rê gô ri viết",
    "antôninôvít": "an tô ni nô viết",
    "dominhcô": "do minh cô",
    "stanilaovít": "sờ ta ni lao viết",
    "nêriô": "nê ri ô",
    "alyllôtôđệbergamô": "a ly lô tô đệ bê ga mô",
    "ekhiriô": "ê khi ri ô",
    "bôniphathiô": "bô ni pha thi ô",
    "gioannêphômôthi": "dô an nê phô mô thi",
    "ubaladôvít": "u ba la đô viết",
    "anrê": "an rê",
    "phatcabâyông": "phat ca bâ yông",
    "columbanô": "co lun ba nô",
    "columba": "co lun ba",
    "phêlithi": "phê li thi",
    "salô": "sa lô",
    "môni": "mô ni",
    "ubalodô": "u ba lô đô",
    "phôrôphêta": "phô rô phê ta",
    "phidikhia": "phi di khi a",
    "hiêraphôly": "hi ê ra phô li",
    "contantinô": "con tan ti nô",
    "giulio": "giu li ô",
    "sắcrinia": "sắc ri ni a",
    "contantinôphôly": "con tan ti nô phô li",
    "giulianô": "giu li a nô",
    "atanaxiô": "a ta na xi ô",
    "arsiniô": "a si ni ô",
    "garganô": "ga ga nô",
    "chighe": "chi ghe",
    "aricantơ": "a ri can tơ",
    "khêlixiô": "khê li xi ô",
    "xiphuntê": "xi phun tê",
    "phathiô": "pha thi ô",
    "boni": "bô ni",
    "nathiantic": "na thi an tic",
    "caphađôthiahai": "ca pha đô thi a hai",
    "ghêdêthia": "ghê đê thi a",
    "ghéregorid": "ghê gô ri",
    "tôrê": "tô rê",
    "basiliô": "ba si li ô",
    "xinh ông chánh": "kinh ông thánh",
    "basiliô": "ba si li ô",
    "ominhgơ": "do minh cô",
    "qinh ông chánh": "kinh ông thánh",
    "minhgô": "minh cô",
    "stanislaghai": "sờ ta ni sờ lao",
    "cadacôvia": "ca đa cô vi a",
    "roanna": "ro an na",
    "alephônsô": "a lê phôn sô",
    "phutughê": "phu tu ghê",
    "loanna": "lo an na",
    "lôanna": "lo an na",
    "Do mi ti la": "do mi ti la",
    "Pha la o ti la": "pha la o ti la",
    "mynôthiêduphô": "mi nô thi ê du phô",
    "phunthia": "phun thi a",
    "tarathina": "ta ra thi na",
    "ausphithiô": "au spi thi ô",
    "Do mi ti la": "do mi ti la",
    "tremphilithianô": "trem phi li thi a nô",
    "vankheniô": "van khe ni ô",
    "vankhenista": "van khe ni sta",
    "matthêu": "ma thêu",
    "phatmô": "phat mô",
    "domithianô": "do mi thi a nô",
    "aphocalipsi": "a phô ca lip xi",
    "êphêsô": "ê phê sô",
    "apocalipsi": "a po ca lip xi",
    "Latina": "La ti na",
    "domithi": "do mi thi",
    "cordianô": "cor di a nô",
    "cinh ông chánh": "kinh ông thánh",
    "cordianô": "cor di a nô",
    "gianua": "gi a nua",
    "ephima": "ê phi ma",
    "aphôlô": "a phô lô",
    "cordianô": "cor di a nô",
    "aphulia": "a phu li a",
    "xêphuntê": "xê phun tê",
    "cờlêmenthianô": "cờ lê men thi a nô",
    "ephima": "ê phi ma",
    "cordianô": "cor di a nô",
    "aphulia": "a phu li a",
    "innôxenthiô": "in nô xen thi ô",
    "serić": "se ri",
    "harăng": "ha răng",
    "caniơ": "ca ni ơ",
    "Pha la vi a": "pha la vi a",
    "titô": "ti tô",
    "tiôdoda": "ti ô đô đa",
    "eubôdo": "ê u bô đô",
    "xina": "xi na",
    "tradanô": "tra đa nô",
    "thisadêô": "thi sa đê ô",
    "akyliô": "a ki li ô",
    "alybaloto": "a ly ba lô to",
    "oercamo": "ô er ca mô",
    "viôna": "vi ô na",
    "verca": "ver ca",
    "ghêđêmôna": "ghê đê mô na",
    "ghêđêmônenxi": "ghê đê mô nên xi",
    "bercômenxi": "bơ cô men xi",
    "alibalôtô": "a li ba lô tô",
    "alibalôtô": "a li ba lô tô",
    "điơ": "đi ơ",
    "đominhgỗ": "do minh cô",
    "phaotyla": "pha o ty la",
    "oniphathirs": "o ni pha thi rô",
    "êkhidiô": "ê khi di ô",
    "êkhiđiô": "ê khi đi ô",
    "agalae": "a ga la e",
    "agalae": "a ga la e",
    "tarsô": "ta r sô",
    "điôcờ": "đi ô cờ",
    "lêthianô": "lê thi a nô",
    "maximianô": "ma xi mi a nô",
    "bôniphathio": "bô ni pha thi ô",
    "phatirithiô": "pha ti ri thi ô",
    "manikêô": "ma ni kê ô",
    "cartagô": "car ta gô",
    "ambrôxiô": "am bô xi ô",
    "phôntithi": "phôn ti thi",
    "victôri": "vi cô ri",
    "semphilythianô": "sem phi li thi a nô",
    "phôntithianô": "phôn ti thi a nô",
    "alyphi": "a ly phi",
    "garathia": "ga ra thi a",
    "alyphi": "a ly phi",
    "midiôlanô": "mi di ô la nô",
    "ađêôsatô": "a đê ô sa tô",
    "ambrôsiô": "am bô xi ô",
    "dêumba": "đê u m ba",
    "bôlúc": "bô lúc",
    "sébomosiđó": "sê bô mo xi đô",
    "bôêmia": "bô ê mi a",
    "ubiênthiếtlao": "u bi ên thi ết lao",
    "ubiênthiếtlao": "u bi ên thi ết lao",
    "êmiliav": "ê mi li a v",
    "canônicô": "ca nô ni cô",
    "yêucubiô": "yêu cu bi ô",
    "hônôriô": "hô nô ri ô",
    "abiloni": "a bi lô ni",
    "anre": "an rê",
    "ponphesode": "pon phe so đê",
    "macximinô": "mac xi mi nô",
    "côngphếtsôđê": "công phết sô đê",
    "scali": "sờ ca li",
    "bayong": "ba yông",
    "tôriphormôsa": "tô ri phô mô sa",
    "sangtô": "sang tô",
    "phiritô": "phi ri tô",
    "phátscaly": "phát sờ ca ly",
    "qenanthić": "quen an thi",
    "cinh ông chánh": "kinh ông thánh",
    "camiri": "ca mi ri",
    "antiôcô": "an ti ô cô",
    "anastasiô": "a na ta xi ô",
    "phorphiriô": "phôr phi ri ô",
    "camiri": "ca mi ri",
    "vênanthiô": "vê na thi ô",
    "vênanthiô": "vê na thi ô",
    "phêrd": "phê rờ đê",
    "celestino": "ce le sờ ti nô",
    "isernia": "i sờ ni a",
    "tremphilithianô": "trem phi li thi a nô",
    "tremphilythianô": "trem phi li thi a nô",
    "milanô": "mi la nô",
    "venus": "ve nớt",
    "dalêna": "đa lê na",
    "ubalôsô": "u ba lô sô",
    "saxerdote": "sa xơ đô tê",
    "êuđêlianô": "êu đê li a nô",
    "akuliô": "a cu li ô",
    "bôniphaxiô": "bô ni pha xi ô",
    "bôniphaxiô": "bô ni pha xi ô",
    "xêlestinô": "xe le sờ ti nô",
    "nicôlao": "ni cô lao",
    "xêlestinô": "xe le sờ ti nô",
    "êmilia": "ê mi li a",
    "nicôlao": "ni cô lao",
    "atôlô": "a tô lô",
    "anastasiố": "a na ta xi ố",
    "ghêlêmentê": "ghê lê men tê",
    "domingô": "do min cô",
    "lêong": "lê ong",
    "bênadu": "bê na đu",
    "maiô": "ma i ô",
    "êmilia": "ê mi li a",
    "lespônenxi": "le sờ nên xi",
    "visensi": "vi sên xi",
    "răngcathiô": "răng ca thi ô",
    "phirirkia": "phi ri ki a",
    "riôcơlithianô": "ri ô cơ li thi a nô",
    "aurelianô": "au re li a nô",
    "êuđêlianô": "êu đê li a nô",
    "ghêlêmentê" : "ghê lê men tê",
    "bôniphaxiô" : "bô ni pha xi ô",
    "anastasiố" : "a na ta xi ố",
    "bênadu" : "bê na đu",
    "minô" : "mi nô",
    "êmilia" : "ê mi li a",
    "miđiôlanô" : "mi đi ô la nô",
    "antong" : "an tong",
    "miđiôlanô" : "mi đi ô la nô",
    "xilythia" : "xi ly thi a",
    "lespônenxi" : "le sờ nên xi",
    "visensi" : "vi sên xi",
    "răngcathiô" : "răng ca thi ô",
    "phirirkia" : "phi ri ki a",
    "aurelianô" : "au re li a nô",
    "êuđêlianô" : "êu đê li a nô",
    "excômônhông" : "ê xơ mô nhông",
    "navikhiô" : "na vi xi ô",
    "âuđêa" : "âu đê a",
    "giustina" : "giu s ti na",
    "aliphi" : "a li phi",
    "phatrixiô" : "pha tri xi ô",
    "basilysa" : "ba si ly sa",
    "phê li thia" : "phê li thi a",
    "navikhiô" : "na vi xi ô",
    "phatrixiô" : "pha tri xi ô",
    "calôva" : "ca lô va",
    "arones" : "a ro nes",
    "vênus" : "ve nớt",
    "mylanô" : "my la nô",
    "giulio" : "giu li ô",
    "phalansa" : "pha lan sa",
    "nôphôly" : "nô phô li",
    "bithanthiô" : "bi than thi ô",
    "tymôthiô" : "ty mô thi ô",
    "contăngtinô" : "con tăng ti nô",
    "yêuxibiô" : "yêu xi bi ô",
    "alecsanrô" : "a lec san rô",
    "nithia" : "ni thi a",
    "alecsanrô" : "a lec san rô",
    "aléesanria" : "a lê san ria",
    "ichitô" : "i chi tô",
    "alecsandô" : "a lec san đô",
    "asia" : "a xi a",
    "natanaê" : "na ta na ê",
    "bitanhthiô" : "bi than thi ô",
    "maisen" : "mai sen",
    "tymôthiô" : "ty mô thi ô",
    "contăngtinô" : "con tăng ti nô",
    "alecsanrô" : "a lec san rô",
    "nithia" : "ni thi a",
    "alecsanrô" : "a lec san rô",
    "aléesanria" : "a lê san ria",
    "ichitô" : "i chi tô",
    "alecsandô" : "a lec san đô",
    "asia" : "a xi a",
    "natanaê" : "na ta na ê",
    "maisen" : "mai sen",
    "vankhêniô" : "van khê ni ô",
    "vankhêlista" : "van khê li sờ ta",
    "aphôcalípsi" : "a phô ca líp xi",
    "giêđônimô" : "giê đô ni mô",
    "phátmô" : "phát mô",
    "giêbêdêô" : "giê bê đê ô",
    "giêđônimô" : "giê đô ni mô",
    "santiximô" : "san ti xi mô",
    "ingờri" : "in gờ ri",
    "mônrôviđô" : "môn rô vi đô",
    "berdamô" : "ber da mô",
    "boscô" : "bô sờ",
}
